import MainNavigation from "./MainNavigation";
import "./globals.css";
import roboto from "../constants/localFonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log(children);
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans`}>
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
